spring:
    application:
        name: user

server:
    port: 8080
        
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8999/eureka/

management.health.circuitbreakers.enabled: true
management.endpoints.web.exposure.include: health
management.endpoint.health.show-details: always

resilience4j.circuitbreaker:
    instance: 
        user: 
            registerHealthIndicator: true
            eventConsumerBufferSize: 10
            failureRateThreshold: 60
            minimumNumberOfCalls: 6
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 3s
            permittedNumberOfCallsInHalfOpenState: 2
            slidingWindowSize: 10
            slidingWindowType: COUNT_BASED
            
            
            
           